### ISSUE TITLE
2.3.1 Finalize AdM's fake country IP addresses

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#11]
Per the [Adm - Firefox Partnership Review](https://docs.google.com/document/d/1wzWRj9ytRs1Mgxu4f8irNQ76YYyUo6c-syCx7FmQmhI/edit#), the AdM hardcoded IP addresses representing countries "will be updated/finalized soon".

This issue's a placeholder to ensure that list is finalized before we roll it out to prod. The mapping will be configurable via a setting.

**Comment by jrconlin** [comment]
Closed as OBE. 

Fake country will not be used in favor of geo-ip derived real country.

In addition, we are using "USOK" for unresolved IPs.
