### ISSUE TITLE
Missing Code of Conduct file 📝

### ISSUE THREAD

**Issue by hackebrot** [mozilla-services/contile#118]
The repository contains a CONTRIBUTING guide, but no CODE_OF_CONDUCT. GitHub lists [the mozilla-services default][org default] under "Helpful resources", but I think it would be good to add this to the repo so it can be found more easily.

[org default]: https://github.com/mozilla-services/.github/blob/850150c44594db082aab8367f90e4004a2d0681f/CODE_OF_CONDUCT.md

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-146)

**Comment by pjenvey** [comment]
Closed in #119
