### ISSUE TITLE
Emit a metric for location lookup failing

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#120]
We forgot to add a metric for the case of location lookup failing #95.

This isn't critical at the moment but I think it's still worth adding at some point.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-147)

**Comment by jrconlin** [comment]
Taking the liberty to add a bunch of other metrics as well.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

closed as part of feat: add more metrics #130 ( https://github.com/mozilla-services/contile/pull/130 )
