### ISSUE TITLE
Allow setting an advertiser "ignore"

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#123]
We're reporting "unknown" advertisers as an event to sentry (#50) for a couple reasons.

We may want a setting for explicitly "ignoring" certain advertisers to no longer report this entry to sentry. Particularly as every pod currently acts independently, logging each event on their own (resulting in duplicates), cluttering the Sentry dashboard.

E.g.:

- Sentry reports a new advertiser of "Acme"
- Ad Ops decides we do not want it included
- Set "Acme" for ignore so the events are no longer generated

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-148)

**Comment by jrconlin** [comment]
Wondering how this list should be specified.
Does it make sense to just be a discrete list or a new entry in the ADM settings?

**Comment by pjenvey** [comment]
"ADM Settings" suggests everything should live in this setting but we probably should have named it something else (there's already other adm settings).

I'm not sure Ad Operations cares much about this list, maybe it mostly ends up being for our own sake to quiet sentry events? In that case it's easier to make it a separate setting. But then we could have clashing settings (ad ops includes "Acme" but we previously set it as an "ignore"). Maybe then the ADM_SETTINGS inclusion trumps the ignore and emits a warning? 🤷‍♂️
