### ISSUE TITLE
Create a mock server that implements the adM API spec for testing

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#126]
AdMarketplace is working on their API for suggestions, however it won't be ready for some time. Having a server that follows the specs we've been given would be helpful for development, and having a local server will be useful for automated tests now and in the future.

We should create a web service that implements the "Conducive Privacy Search" API (4.9.21, as of this writing). This is the same API that [merino-adm/src/server_side.rs](https://github.com/mozilla-services/merino/blob/abbc1a99127bd214aaaf36e8f5d85acc53a0124e/merino-adm/src/server_side.rs) is targeted ad. It should support both randomly generated data (for manual testing), and the ability to specify mock data to be used for requests (for automated testing).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-80)

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

A couple of features of the top of my head:

  * This mock server could serve both Contile and Merino
  * Being able to run it both locally and publically (containerized) 
  * Contile and Merino can be configured to hit this mock server
  * Being able to support multiple Conducive API versions, basically all the versions that Contile/Merino have worked with
  * Easy to expand and maintain (as it needs to support all the previous API versions)
  * Performance is a non-goal here

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

After talking with mythmon, we don't believe this mock server will be super useful for Merino right now as it could treat RemoteSettings (`quick-suggest`) as the mock data source.

[~pjenvey@mozilla.com] - Do you think Contile will find it useful now? If not, let's leave it in the backlog, we can revisit it in the future.

**Comment by data-sync-user** [comment]
➤ Raphael Pierzina commented:

I started building a mock server that allows us to run integration tests on Contile without relying on the external AdMarketplace API.

**Comment by jrconlin** [comment]
Contile has a feature already where you can set a flag and the service [can read "mock" data](https://github.com/mozilla-services/contile/blob/main/src/adm/tiles.rs#L145-L155) from files. This happens at the point where the ADM server is called, and gives the ability to test non-standard returns.

**Comment by data-sync-user** [comment]
➤ Michael Cooper commented:

Removed Merino from this, since the current work is Contile-focused, and it is unclear if Merino needs something like this.
