### ISSUE TITLE
Metric adm::get_tiles calls

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#138]
Visibility into how frequently we're querying for tiles from ADM would be useful, let's add a simple counter metric for this.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-179)

**Comment by jrconlin** [comment]
There is a metric call on [`handlers/get_tiles()`](https://github.com/mozilla-services/contile/pull/130), which should suffice. Do you want one that is explicitly for adm?

**Comment by pjenvey** [comment]
> There is a metric call on [`handlers/get_tiles()`](https://github.com/mozilla-services/contile/pull/130), which should suffice. Do you want one that is explicitly for adm?

Yea, since they're isn't a 1:1 mapping of ``handler::get_tiles`` to the call to adm (``adm::get_tiles``)
