### ISSUE TITLE
Wire in Maxmind as the primary location lookup source

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#149]
With us already seeing situations like #148 it makes sense to try out maxmind in case it results in less failed location lookups.

Let's finish wiring this into the app and use maxmind as the primary location lookup source, while still falling back to the LB header if it fails.

Let's ping SRE (@jbuck) on how to integrate the commercial version into contile.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-196)

**Comment by jrconlin** [comment]
The code is already wired up to use the Max Mind database (if there is one defined in the `maxminddb_loc` setting), and will fail back to looking for the LB header if a lookup produces an error. We do not attempt to back fill from the Header and would need to add code if that is desired.

**Comment by jbuck** [comment]
https://github.com/mozilla-services/cloudops-infra/pull/3193

**Comment by pjenvey** [comment]
This need some [additional work](https://github.com/mozilla-services/contile/pull/155#issuecomment-861857026) to follow up #155
