### ISSUE TITLE
Tile Images to CDN (Contile image hosting)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#167]
Store images provided in the adM Instant Suggest tiles to our own Content Distribution Network (CDN) system. This is the top priority for Contile v2.

Business need: Updates to existing built-in advertiser icons have to ride the train, which is too long of a delay if an icon needs to be updated for any reason. The ability to update images off-train is also a key value prop of Contile.

Privacy need: This would increase user privacy by potentially not leaking information to an unknown CDN.

[https://github.com/mozilla-services/contile/issues/19](https://github.com/mozilla-services/contile/issues/19)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-33)
┆Epic: Contile v2

**Comment by data-sync-user** [comment]
➤ Amy Tsay commented:

This has been moved up in priority because there is a business impact of images needing to ride the trains when updated.

**Comment by pjenvey** [comment]
> This has been moved up in priority because there is a business impact of images needing to ride the trains when updated.

per @ncloudioj (who recalled this fact after the recent meeting discussing this topic) -- image updates don't need to ride the trains as they can be updated more quickly via the [tippytop remote settings bucket](https://firefox-source-docs.mozilla.org/browser/components/newtab/docs/v2-system-addon/tippytop.html).

Contile should still handle storing images on the CDN anyway to streamline this process but the priority may not be as high.

**Comment by ncloudioj** [comment]
It just occurred to me that Tippytop can only be used to fill the missing images, but can't update the images as the builtin images would take precedence over Tipppytop in Firefox.

We might still want to prioritize this feature in H2.

**Comment by jrconlin** [comment]
Ops bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1720525

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Ops bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1720525 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1720525|smart-link )

**Comment by data-sync-user** [comment]
➤ Ron Manning commented:

JR Conlin https://mozilla-hub.atlassian.net/browse/FIDE-585 ( https://mozilla-hub.atlassian.net/browse/FIDE-585|smart-link ) is Closed, should we also close this ticket?

**Comment by jrconlin** [comment]
No, because that only addresses the Client side. There is still a PR
pending approval for server work:
https://github.com/mozilla-services/contile/pull/212
