### ISSUE TITLE
Render actual JSON error responses

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#177]
To aid in debugging we should return actual JSON error responses -- we currently return a payload of the error's status code, inherited from syncstorage-rs.

Technically this is json as we're sending `Content-Type: application/json` and a number, but this should be more along the lines of our other services's, e.g. megaphone's:

```
$ curl https://dev.megaphone.nonprod.cloudops.mozgcp.net/nonexistant
{"code":404,"errno":123,"error":"Not Found"}
```

Let's double check this won't affect the client but I believe it currently only cares about the http status code.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1089)
┆epic: Contile maintainablity enhancements

**Comment by jrconlin** [comment]
There's some existing code that might be a good template for this in both [Megaphone](https://github.com/mozilla-services/megaphone/blob/master/src/error.rs#L143-L180) and [Autopush](https://github.com/mozilla-services/autopush-rs/blob/master/autoendpoint/src/error.rs#L248-L263). Either approach should work.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

https://github.com/mozilla-services/contile/pull/353 ( https://github.com/mozilla-services/contile/pull/353|smart-link )
