### ISSUE TITLE
3.2.2.3 Support filtering and metadata configuration of Tiles

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#18]
We need the ability to:

- restrict which tiles are presented to the client
- addition of metadata to each tile

**Comment by pjenvey** [comment]
@ncloudioj The current top-sites bucket has an `include/exclude-regions` field. Will contile need the ability to include advertisers by region at this point?

E.g. we may want to include Yandex but only in the RU region. However adM might only return Yandex when contile asks for RU Tiles anyway. What I'm getting at is does the top-sites' buckets' `include/exclude-region` exist only to workaround the bucket including data for all regions (these include/excludes are specified by adM) or do we use it for our own curation purposes?

**Comment by pjenvey** [comment]
The only metadata we need added is a `position` field. E.g. include the "Amazon" tile with a position of 1.

The other 2 bits that should likely be defined with the inclusion filter are an allow list of hostnames `advertiser_url` may reside on. At some point when we begin serving images through the CDN (and the client actually uses them, they currently do not), approved by a human `image_url` configuration would also be defined with the inclusion filter.

E.g. include the "Amazon" tile with a position of 1, url allow list of [amazon.com, amazon.ca]. And later, additionally with an image allow list of probably a sha1?

**Comment by jrconlin** [comment]
I had originally thought that the list of sites would be fairly small, but what you're describing makes me think that the rules could get fairly complex quickly. Enough to already make me wonder if using a centralized db to store the filter criteria might be a better option, even if there's some criteria duplication possible. (e.g. 
a schema of  "id", "country","region", "lang" where a given ID would be shown, unless there was a filter specified, and then it would use that filter to determine viewership.

for example:

| rule | description |
|-|-|
| "123", "us", None, None | display partner "123", if the client IP reports being in the "US" |
| "456", "ca", "bc", "en" | display partner "456" only in British Columbia, CA if the UA reports being set to "English" |

etc.

Granted, this does potentially raise a lot more questions (who has access to that DB, how are changes performed, how are they audited, etc.) but it does mean that changes could be reflected quickly, tiles could be brought down or up with greatly reduced propagation, and we have a fair bit of control over display.
