### ISSUE TITLE
Move ADM Settings to a common data store

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#202]
The current JSON based ADM settings structure is not very scalable. We should consider moving it to a common data store so that only a single update is required to change values, and no re-deploy is required.

This will require a bit of thought around what storage system to use, the appropriate schema, and how access to the data store would be controlled.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1102)
┆epic: Contile Settings Manager

**Comment by hackebrot** [comment]
Something that we need to think about for when updating the ad settings doesn't require a contile re-deploy is how we invalidate cached tiles. Do we filter tiles based o the settings after we read them from the cache? Do we request new ones if that could mean that no tiles are returned to the client?

**Comment by jrconlin** [comment]
There are a few ways that we could deal with this. One would be to use the emergency cache purge option (see #170 ), but that might be a bit too dramatic. Another would be to let the tiles naturally age out of the cache and then let the new tiles propagate in.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

With the re-architecture of the Contile Settings (See proposal ( https://docs.google.com/document/d/1sMya9PA6CcgvB0axJeMZtDpudYxGmly7_xCVEn5LgYY/edit )), this function can be rolled up into the settings management.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

With the re-architecture of the Contile Settings Manager (see proposal ( https://docs.google.com/document/d/1sMya9PA6CcgvB0axJeMZtDpudYxGmly7_xCVEn5LgYY/edit )), this function can be rolled up.
