### ISSUE TITLE
Shared tiles cache

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#210]
Currently, each instance of Contile keeps an "in memory" cache of served tiles. Tiles tend to be small and memory is not a significant issue at this time, but we should consider if a shared cache (e.g. REDIS or similar) may simplify things. (e.g. if we need to kill a tile quickly, removing it from a shared cache may be preferable than either walking the server list or letting the tile expire naturally.)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1116)
┆Epic: Contile v2

**Comment by jrconlin** [comment]
Closing this in favor of creating [a Jira Epic](https://mozilla-hub.atlassian.net/browse/CONSVC-1116) to encapsulate tasks.
