### ISSUE TITLE
Extract Contile's location parsing into common-rs

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#215]
All of our services should use the same location parsing strategy. Contile already has a deployed location parsing system. This should be extracted to a crate in [mozilla-services/common-rs](https://github.com/mozilla-services/common-rs/). This crate can then be used in Contile, Merino, and Channel Server.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1145)
┆Epic: merino-m0

**Comment by mythmon** [comment]
https://crates.io/crates/actix-web-location 0.1.1 is ready to use.
