### ISSUE TITLE
Rate limit calls to adM in downtime conditions

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#220]
When there's issues with the adM tile API service (e.g. timeouts), contile can end up queuing a large (too many) number of requests to adM. We should restrict the number of total connections initiated, likely 503ing to clients when there's too many.

**Acceptance Criteria:**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-1153)

**Comment by jbuck** [comment]
Yeah, when there's too many 5xx errors from AdM, a triggering a [circuit breaker](https://martinfowler.com/bliki/CircuitBreaker.html) in contile to limit the number of outbound connections would be perfect

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

https://github.com/mozilla-services/contile/issues/220 ( https://github.com/mozilla-services/contile/issues/220|smart-link ) has significantly reduced the adM calls even during downtime cases.

This can be further improved but I think this reduction has moved this to lower priority.
