### ISSUE TITLE
Filter outbound advertisers based on UA version number

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#246]
We will need to limit the campaigns we display based on the User Agent version. This is because 91+ allows for pulling images from CDN where -91 can only use internal images. 

This should be a temporary fix, and noted as such. 

This will require creating a list of limited campaign advertisers to allow for versions of Firefox less than 91. Any ADM provided advertiser that is not contained in that list should be dropped from the set of tiles returned to the UA. 

Coordination with QA regarding integration testing will be required.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1181)
┆Epic: Contile v2

**Comment by data-sync-user** [comment]
➤ Raphael Pierzina commented:

We’ll need to update the User-Agent headers in the following file for the integration tests https://github.com/mozilla-services/contile/blob/main/tools/volumes/client/scenarios.yml ( https://github.com/mozilla-services/contile/blob/main/tools/volumes/client/scenarios.yml|smart-link )

**Comment by pjenvey** [comment]
Thinking of the simplest way of adding this, it could be managed more on the Ad Ops side by adding a new flag in the inclusion filter indicating `no_legacy_image` and adding some kind of legacy flag to `DeviceInfo` and the cache's `AudienceKey`.

This would probably double the size of the cache but that's not a big concern.

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

I did an intersection between this ( https://searchfox.org/mozilla-central/source/browser/components/newtab/data/content/tippytop/images ) (packaged images) and this ( https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=FPS&title=Mozilla+Approved+Advertisers#MozillaApprovedAdvertisers-SponsoredTopSitesTiles ) (approved advertisers) with this inclusion list:

adidas
amazon
ebay
etsy
geico
nike
samsung
wixFor requests from Firefox 90 and below, let’s filter all the advertisers that are on the above list.

**Comment by jrconlin** [comment]
Closed via #247
