### ISSUE TITLE
improve image cache management with shared cache

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#251]
Use an external cache management system to manage image handling between active nodes.

This is because it can take time to fetch, process, and store a tile image, and during peak loads we don't want to provide broken images or storm the storage system with storage requests.

It was recommended to use redis as the external cache management tool.

This may also relate to #202

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-1185)
┆Epic: Contile Shared tiles cache

**Comment by pjenvey** [comment]
I'm not sure that triggering the Object rate limit is that much of a problem. If we're hitting the rate limit hasn't at least one of the writes succeeded (see #252)? And If so I don't see how we would have broken images.

**Comment by jrconlin** [comment]
Well, that error definitely answers the question of "does google cloud storage report file status during a partial write". (Somewhat related, I should probably convert that `read()` to `list_prefix`, which is lighter weight.)

I don't believe that hitting the rate limit implies that any of the writes succeeded. Just that there are a whole lot of attempted writes with churn at the end. I'm also thinking that if we have a lot of concurrent writes, we're relying on all of those writes to complete correctly, which could be a bit of a crap shoot.
