### ISSUE TITLE
Re-enable automated integration tests

### ISSUE THREAD

**Issue by hackebrot** [mozilla-services/contile#254]
The **contile-integration-tests** were disabled in #247 because that pull request didn't pass the integration tests.

We need to re-enable the integration tests as soon as possible to make sure we catch integration issues with Contile.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1188)

**Comment by hackebrot** [comment]
The test for invalid `UserAgent` headers failed because the current revision uses a Firefox header for this test. I'll revert that particular `UserAgent` header to Safari.

**Comment by pjenvey** [comment]
Closed in #255
