### ISSUE TITLE
Support dma-code in location_test_header

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#269]
Follow up to #205:

The location test header should allow testing clients to additionally specify a dma-code, ensuring we're able to better simulate a cache similar to the production environment's.

Then we'll need a new issue for contile-loadtest to utilize it, sending random dma-codes (or omitting dma codes) for US regions. Ideally they wouldn't be _too_ random -- there should only so many DMA codes used per individual US state.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1226)

**Comment by jrconlin** [comment]
IIRC, the MMDB test library provides a DMA code as part of their delivery.
I'm wondering if we should overload the `X-Test-Location` header to contain this info? (e.g. what to have our fake location service return)

**Comment by pjenvey** [comment]
> I'm wondering if we should overload the `X-Test-Location` header to contain this info?

That's what I meant here, I've just done a quick impl. we could include w/ #264.

Then it would be up to the loadtester to fill it in appropriately
