### ISSUE TITLE
3.1.2 Lookup country/subdivision by IP address

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#30]
Should be done via the MaxMind commercial db

**Comment by pjenvey** [comment]
Reopening as this isn't completely done yet: 

- [x] #49 added maxmind support
- [ ] #51 plugs it in with a fallback to the load balancer headers)
- [ ] the `?country=<country>` url parameter the client specified for phase 0 should be removed

**Comment by jrconlin** [comment]
Closed as OBE.

All issues addressed.
