### ISSUE TITLE
Support an alternative adm_endpoint_url for the mobile form_factor

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#345]
We'll want the ability to use a different adm_endpoint_url (root host) depending on the requested form_factor (in particular the mobile type).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1559)
┆epic: Contile production v1

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

I linked https://mozilla-hub.atlassian.net/browse/CONSVC-1179 ( https://mozilla-hub.atlassian.net/browse/CONSVC-1179|smart-link ) to this as it’s related to how we define settings for partners.

However the requirement is very specific to adM’s needs so we probably just want to implement this as a simple additional setting e.g. adm_mobile_endpoint_url.

**Comment by data-sync-user** [comment]
➤ David Durst commented:

Assigning this to JR based on the open PR

**Comment by jrconlin** [comment]
Closed as part of #346
