### ISSUE TITLE
The "postion" field is not always populated in the response of Contile 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#347]
The mobile team noticed that sometimes the “position“ field was populated as “null“ rather than an integer in Contile’s response.

This won’t affect desktop as Firefox doesn’t use this field right now. Though mobile team does reference it, so let’s ensure this field is always populated with a valid value in the response.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1586)

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

What should the value be if it’s not provided by ADM? (the adjusted position? a static high value to indicate no preference? etc.)

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

Since this `position` field is not currently used by desktop, nor would it provide any meaningful guidance to mobile consumers. We’ve decided to drop it from the API response to avoid confusion. We will bring it back in the future when we have a clear use case for it.

Note that this would not be a breaking API change as no Contile consumers are using it.

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Linking to https://mozilla-hub.atlassian.net/browse/CONSVC-1562 ( https://mozilla-hub.atlassian.net/browse/CONSVC-1562|smart-link )  because of https://github.com/mozilla-services/contile/pull/346 ( https://github.com/mozilla-services/contile/pull/346|smart-link )

**Comment by data-sync-user** [comment]
➤ JR Conlin commented:

Including reference to https://mana.mozilla.org/wiki/display/FJT/Removal+of+the+`position`+field+from+Contile+output ( https://mana.mozilla.org/wiki/display/FJT/Removal+of+the+%60position%60+field+from+Contile+output )

**Comment by jrconlin** [comment]
Closed as part of #346
