### ISSUE TITLE
Report DNS resolution errors in `__lbheartbeat__`

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#358]
It is possible for nodes to fail due to DNS errors. This can lead to repeated attempts to connect, which leads to more DNS failures. 

We should note repeated DNS lookup errors as a failure state in `__lbheartbeat__` so that SRE can determine node health and automate accordingly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-1633)

**Comment by pjenvey** [comment]
I think we should wait for #357 to land before implementing this as I'm hoping it would make this basically a non-issue.

**Comment by jrconlin** [comment]
Potentially agree. This ticket is a byproduct of the incident review.

**Comment by ddurst** [comment]
So is this now a non-issue?

**Comment by jrconlin** [comment]
yes. closing issue.
