### ISSUE TITLE
3.4 Valid tiles should be returned to the UA in expected format

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#38]
Tile responses #36  that have been validated #37 or taken from the cache #34 should be returned to the UserAgent as JSON

*NOTE* Final JSON format TBD.

**Comment by pjenvey** [comment]
Finalized in the [Technical Overview](https://docs.google.com/document/d/12hV_4b6Ur_rpdk1ic7OYOVL_v6i_F886RGXtch60-qg/edit?userstoinvite=dgottwald@mozilla.com&ts=60a38ac6) and already implemented
