### ISSUE TITLE
3.5.2 Create an internal service endpoint to emergency purge the cache

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/contile#40]
This entry point should force purge all records from the cache.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-205)
┆Epic: Contile Shared Cache

**Comment by data-sync-user** [comment]
➤ Philip Jenvey commented:

Duplicate of https://mozilla-hub.atlassian.net/browse/CONSVC-207, closing
