### ISSUE TITLE
Update Suggestion schema to match Firefox's expected schema

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#53]
The current [Remote Settings based suggester in Firefox](https://searchfox.org/mozilla-central/rev/71515d047cbdd02687a1b9b7265f2ffb51300bf1/browser/components/urlbar/UrlbarQuickSuggest.jsm#95-106) uses the below schema

```javascript
{
  fullKeyword: string, // if the user typed "sho" to match "shoes", then this is "shoes"
  title: string,
  url: URL, // with `%YYYYMMDDHH%` replaced with the current date+hour
  click_url: URL, // with date replacement
  impression_url: URL, // no date replacement
  block_id: string, // The suggestion's record ID
  advertiser: string,
  isSponsored: boolean,
  icon: URL, // this is the actual image in the client, but should be the URL in Merino
};
```

The `merino_suggest::Suggestion` struct should correspond closely to this schema, to make future integration simpler.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/CONSVC-58)

**Comment by mythmon** [comment]
This was mistakenly synced to the wrong repo. This isn't relevant to contile.
