### ISSUE TITLE
100% Release population sees sponsored tiles served by Contile

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#74]
Acceptance criteria:

* Load tests pass
* Integration tests pass
* High level of confidence based on pre-release channel rollouts
* QA sign-off

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-98)

**Comment by mythmon** [comment]
I added nosync to the jira side, we don't need to track this in github.
