### ISSUE TITLE
Support "hardcoded" tiles

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#81]
We need the ability to configure a Tile not served from upstream (adM).

We can specify this in the inclusion filter alongside other advertisers, maybe with an explicit flag there to denote it should be included regardless of whether we see it served from upstream.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-104)

**Comment by pjenvey** [comment]
One example of an initial advertiser that would be "hardcoded" has the following properties:

1. No click/impression urls, we simply serve a landing page
2. The landing page may differ by region

Unfortunately our current `AdmSettings` json doesn't yet accommodate #2

**Comment by jrconlin** [comment]
There's a lot of things that AdmSettings doesn't support. It's absolutely a band-aid to a larger problem.
(e.g. for "hardcoded" we might want to only serve it _n_% of the time, or rotate it with _i_ number of alternates, or...)

All that kinda says that we need to have a separate tile management system in addition to whatever we poll from adM.

**Comment by data-sync-user** [comment]
➤ Amy Tsay commented:

Filed in backlog as this is not an MVP for Fx90 delivery. Use case of overriding Contile with hardcoded tiles can be handled using the current Remote Settings implementation.
