### ISSUE TITLE
Define Contile HTTP status codes

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#92]
Let's use this ticket to specify the HTTP status code for Contile, then we can add the specs to the Contile technical [doc](https://docs.google.com/document/d/12hV_4b6Ur_rpdk1ic7OYOVL_v6i_F886RGXtch60-qg/edit?usp=sharing).

We should cover the following cases:

* Success - Contile was able to answer user's request with at least one tile either from cache or adM
* Failure case (1) - All the tiles from adM failed to pass the validation
* Failure case (2) - Contile or adM errored with 500
* Failure case (3) - Contile received other error codes (such as 40X) from adM

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-117)

**Comment by jrconlin** [comment]
I'm going to suggest the following:

Success (with tiles): 200
Failure 1 - no tiles: 204 NO_CONTENT
Failure 2 - adm 500 error: 502 BAD_GATEWAY
Failure 3 - adm general error: 503 SERVICE_UNAVAILABLE.

The last may be a bit odd, since you normally also provide a "Retry-After:" response header. We still could, and just provide a Period + Random second value to alleviate thundering herd problems.

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

Firefox currently treats the HTTP 200 with an empty tile array as "we don't have anything to show right now", hence it won't show any sponsored tiles even if there are some from the last response.

On the other hand, if Contile responds the request with any error code, Firefox will only record an error and leave the existing sponsored tiles (if any) alone.  

I think there is some kind of ambiguity between "have nothing to show" vs "we do have something from adM, but they didn't the validation, maybe you can reuse the existing ones until we get those new ones fixed". Either way, let's define a set of status codes for Contile so that Firefox devs can reference.

**Comment by jrconlin** [comment]
hrm, not to bikeshed too much, but tempted to switch failure 2 and failure 3 returns 
(so an ADM 500 would result in Contile returning a `503 SERVICE UNAVAILABLE` and a non 500 ADM error would return a `502 BAD GATEWAY`)

The rationale being that an ADM 500 would clear faster than one of the other errors, but again, this feels like bike-shedding.

**Comment by data-sync-user** [comment]
➤ Nan Jiang commented:

[~jconlin@mozilla.com] - I like your proposal.

I was also thinking about a protocol between Firefox and Contile such that If Contiles knows there are tiles campaigns running in certain areas (perhaps adM's API can help us with this), then it can return something back to Firefox to signify that so it won't request over and over again.

FWIW, Firefox current will ping Contile every 15 mins for new tiles if the sponsored TopSites feature is enabled, and this feature is default on for everyone unless they manually turn it off.
