### ISSUE TITLE
Phase 2: MVP Features Complete

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#94]
By May 25, deploy Contile MVP features to production and flip pref so Nightly users will start seeing tiles served by Contile.

Acceptance criteria:

* adM production endpoint is ready - DONE
* Ops sign-off on stage - TO DO
* Experimenter ticket filed and Normandy team engaged - DONE

┆Issue is synchronized with this [Jira Epic](https://jira.mozilla.com/browse/CONSVC-109)

**Comment by data-sync-user** [comment]
➤ Ron Manning commented:

adM Response Filter is complete

Tile Validation: We are doing some validation to the query parameters included in Tile URLs

Stage Server Ready: We filed a bug deploy Contile 0.1.0 to Stage

**Comment by atsay** [comment]
Closed bc syncing is not needed for epics.
