### ISSUE TITLE
Handle location lookup failing

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/contile#95]
Currently `LocationResult` returns empty strings for country/subdivision in the case that their lookup failed.

We don't want to emit empty strings anywhere (to adM, in our cache keys or to metrics/sentry) and the adM response w/ one would likely be an error.

There's not much we can do when lookup fails, I think we should probably:

1. default to some common location (say US-NY) so something is shown
2. emit a metric about the lookup failure

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-118)

**Comment by jrconlin** [comment]
I'm going to make this a setting for now. `CONTILE_DEFAULT_LOCATION`. Also tempted to use `USOK`, since that's where my newly registered IP address winds up getting located for sites that haven't updated their GEOIP lookups for over 2 years.

**Comment by pjenvey** [comment]
Logged #120 for an associated metric
