### ISSUE TITLE
Production Server ready

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#98]
Deploy a Production server for the Contile service which accesses the appropriate adM server and delivers testable content.

Acceptance criteria:

* Ops signs off on Production

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-125)

**Comment by pjenvey** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1712974
