### ISSUE TITLE
Experimenter readiness for Contile rollout on Nightly

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-services/contile#99]
Normandy ops should be informed as soon as we know we're doing a rollout on Normandy. Experimenter ticket should include information drafted in the rollout plan. 

Acceptance criteria:

* Experimenter checklist is complete
* Experimenter ticket is in "ready to ship" status.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/CONSVC-126)

**Comment by data-sync-user** [comment]
➤ Michael Cooper commented:

The Experimenter ticket is here: https://experimenter.services.mozilla.com/experiments/mozilla-tiles-service-in-nightly/

I'd say this issue should not be marked done yet, because although the ticket is filed, it isn't ready to launch. For that, we would need the status of the ticket to be "Ready to Ship".

**Comment by mythmon** [comment]
I added nosync to the jira side, we don't need to track this in github.
